### ISSUE TITLE
Chat Formatting Error

### ISSUE THREAD

**Issue by BreeOge** [The-Fireplace-Minecraft-Mods/TickDynamic#1]
forge-1.11.2-13.20.0.2282
1.11.2 Minecraft

java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
at com.wildex999.tickdynamic.commands.CommandHandler.func_184881_a(CommandHandler.java:94) ~[TickDynamic-1.11.2-0.5.0.jar:?]
at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) ~[k.class:?]
at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:162) ~[MinecraftCommandWrapper.class:1.11.2-2282-6.1.0-BETA-2360]
at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:147) ~[MinecraftCommandWrapper.class:1.11.2-2282-6.1.0-BETA-2360]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-2282-6.1.0-BETA-2360]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-2282-6.1.0-BETA-2360]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) ~[mi.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) ~[mi.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:153) ~[PacketUtil.class:1.11.2-2282-6.1.0-BETA-2360]
at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:159) [CauseTracker.class:1.11.2-2282-6.1.0-BETA-2360]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:152) [PacketUtil.class:1.11.2-2282-6.1.0-BETA-2360]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjk000(SourceFile:539) [fo$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:256) [SpongeImplHooks.class:1.11.2-2282-6.1.0-BETA-2360]
at net.minecraft.server.MinecraftServer.redirect$onRun$zhj000(MinecraftServer.java:3949) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftS

**Comment by BreeOge** [comment]
Should be net.minecraft.util.text.TextFormatting
