### ISSUE TITLE
Possible bug in code

### ISSUE THREAD

**Issue by KristjanKr** [The-Fireplace-Minecraft-Mods/TickDynamic#6]
Log: https://paste.ee/p/TD7RG
What it does?
Spams the console with:
[21:15:39] [Server thread/WARN] [Tick Dynamic]: Failed to remove: shetiphian.terraqueous.common.tileentity.TileEntityDoodad@61de885c as it does not exist in list: com.wildex999.tickdynamic.listinject.ListManager@65e1ed52
[21:15:39] [Server thread/ERROR] [Tick Dynamic]: Contains check: shetiphian.terraqueous.common.tileentity.TileEntityDoodad@4256c5d2 does not belong to list: com.wildex999.tickdynamic.listinject.ListManager@65e1ed52 but instead None
[21:15:39] [Server thread/INFO]: [STDERR]: java.lang.Exception: Stack trace
[21:15:39] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at com.wildex999.tickdynamic.listinject.ListManager.contains(ListManager.java:248)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:355)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at com.wildex999.tickdynamic.listinject.ListManager.removeAll(ListManager.java:385)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.World.func_72939_s(World.java:1844)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[21:15:39] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[21:15:39] [Server thread/WARN] [Tick Dynamic]: Failed to remove: shetiphian.terraqueous.common.tileentity.TileEntityDoodad@4256c5d2 as it does not exist in list: com.wildex999.tickdynamic.listinject.ListManager@65e1ed52

What it should do?: Not spam the console.
TickDynamic version: 0.5.3(built from source)
Forge: build 2315
Minecraft: 1.11.2

It occurs while OTG is doing chunk pregen as could be seen from console aswell.

**Comment by KristjanKr** [comment]
The build is exactly same as from curseforge and the issue stays the same.

**Comment by KristjanKr** [comment]
If it is somehow useful, I will attach other console log aswell, it still spams the log even with terraqueus removed, but now because of other mod:
https://paste.ee/p/3xb87

Have fun fixing this.
