### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Black0305** [The-Fireplace-Minecraft-Mods/TickDynamic#60]
Is there a way to prevent the console spam?

[03:01:08] [Server thread/WARN] [tickdynamic]: Failed to remove: forestry.arboriculture.tiles.TileLeaves@524c82fa as it does not exist in the list.

Not sure what the line says exactly but it is spamming a lot in the console.

**Comment by AndreiTS** [comment]
For me it's spamming [tickdynamic]: Failed to remove: net.minecraft.tileentity.TileEntityBed@5fa368a as it does not exist in the list.

**Comment by Nightseer769** [comment]
Mine is Failed to remove: com.cout970.magneticraft.features.multiblocks.tileentities.TileMultiblockGap as it does not exist in the list.

**Comment by ghost** [comment]
my issue is java.lang.Exception: Stack trace
[13:18:16 WARN]:        at java.lang.Thread.dumpStack(Unknown Source)
[13:18:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
[13:18:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
[13:18:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
[13:18:16 WARN]:        at net.minecraft.world.World.func_72939_s(World.java:2164)
[13:18:16 WARN]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:737)
[13:18:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
[13:18:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
[13:18:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
[13:18:16 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
[13:18:16 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by ghost** [comment]
it just spams this constantly

**Comment by kreezxil** [comment]
@The-Fireplace can you please add a patch that allows us to turn off the tickdynamic messages in console?

```
[19:26:23] [Server thread/WARN] [tickdynamic]: Failed to remove: vazkii.psi.common.block.tile.TileConjured@68d725ec as it does not exist in the list.
[19:26:23] [Server thread/WARN] [tickdynamic]: Failed to remove: mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled@46940bf0 as it does not exist in the list.
```
200 million lines of that is pointless. It doesn't even exist, nothing i can do about it. sure it's in a registry somewhere. this is pack not a mod i can code. so an option to go silent and only report fatals would be most excellent!

**Comment by kreezxil** [comment]
hey guys i think we missed something in the general section of the config.

```
    # Disables all log output to the console. Make sure this is off before providing the author with logs.
    B:nologs=true 
```

**Comment by kreezxil** [comment]
it's false by default.

**Comment by The-Fireplace** [comment]
There is a config option.
