### ISSUE TITLE
relentless console error spam

### ISSUE THREAD

**Issue by xemnes** [The-Fireplace-Minecraft-Mods/TickDynamic#63]
my console is constantly being spammed with this error

05.10 17:44:50 [Server] WARN java.lang.Exception: Stack trace
05.10 17:44:50 [Server] WARN at java.lang.Thread.dumpStack(Thread.java:1336)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
05.10 17:44:50 [Server] WARN at net.minecraft.world.World.func_72939_s(World.java:2164)
05.10 17:44:50 [Server] WARN at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:737)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
05.10 17:44:50 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
05.10 17:44:50 [Server] WARN at java.lang.Thread.run(Thread.java:748)

is there any way to fix it?

**Comment by Xiantrius** [comment]
hi @xemnes
same problem in Minecraft Magma Server 1.12.2
[17:06:54] [Server thread/WARN] []: java.lang.Exception: Stack trace
[17:06:54] [Server thread/WARN] []:     at java.lang.Thread.dumpStack(Unknown Source)
[17:06:54] [Server thread/WARN] []:     at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
[17:06:54] [Server thread/WARN] []:     at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
[17:06:54] [Server thread/WARN] []:     at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.world.World.func_72939_s(World.java:2109)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[17:06:54] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[17:06:54] [Server thread/WARN] []:     at java.lang.Thread.run(Unknown Source)

**Comment by BloxMaster3** [comment]
same problem here with mohist server
[11:38:16 WARN]: java.lang.Exception: Stack trace
[11:38:16 WARN]:        at java.lang.Thread.dumpStack(Unknown Source)
[11:38:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
[11:38:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
[11:38:16 WARN]:        at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
[11:38:16 WARN]:        at net.minecraft.world.World.func_72939_s(MixinWorldRedstone.java:2161)
[11:38:16 WARN]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:744)
[11:38:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:897)
[11:38:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[11:38:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[11:38:16 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1885)
[11:38:16 WARN]:        at java.lang.Thread.run(Unknown Source)
