### ISSUE TITLE
relentless console spam

### ISSUE THREAD

**Issue by xemnes** [The-Fireplace-Minecraft-Mods/TickDynamic#64]
my console is constantly being spammed with this error

05.10 17:44:50 [Server] WARN java.lang.Exception: Stack trace
05.10 17:44:50 [Server] WARN at java.lang.Thread.dumpStack(Thread.java:1336)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManager.remove(ListManager.java:374)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:57)
05.10 17:44:50 [Server] WARN at com.wildex999.tickdynamic.listinject.ListManagerEntities.remove(ListManagerEntities.java:9)
05.10 17:44:50 [Server] WARN at net.minecraft.world.World.func_72939_s(World.java:2164)
05.10 17:44:50 [Server] WARN at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:737)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902)
05.10 17:44:50 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
05.10 17:44:50 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627)
05.10 17:44:50 [Server] WARN at java.lang.Thread.run(Thread.java:748)

is there any way to fix it?

**Comment by juraj-hrivnak** [comment]
```cfg
    # Disables all log output to the console. Make sure this is off before providing the author with logs.
    B:nologs=true 
```

**Comment by InuYasha86000** [comment]
this does not seem to fix the console spam for me, and this seems to happen when players are logged into the server.

**Comment by xemnes** [comment]
Makes sense since this is an error being reported by Java and not the mod
