### ISSUE TITLE
crash (casting problem)

### ISSUE THREAD

**Issue by Yarden-zamir** [The-Fireplace-Minecraft-Mods/TickDynamic#8]
this was a crash which seemed to be from casting to your custom object. is it a problem with something i'm doing or with the 1.10 version of the mod
[2017-06-16-7.log.gz](https://github.com/The-Fireplace/TickDynamic/files/1081806/2017-06-16-7.log.gz)

Encountered an unexpected exception
java.lang.ClassCastException: net.minecraft.tileentity.TileEntityChest cannot be cast to com.wildex999.tickdynamic.listinject.EntityObject
        at com.wildex999.tickdynamic.listinject.ListManager.add(ListManager.java:18) ~[ListManager.class:?]
        at net.minecraft.world.World.func_175700_a(World.java:1899) ~[aid.class:?]
        at net.minecraft.world.World.func_175690_a(World.java:2459) ~[aid.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:622) ~[asv.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:331) ~[aid.class:?]
        at hellfirepvp.astralsorcery.common.util.struct.BlockArray.placeInWorld(BlockArray.java:173) ~[BlockArray.class:?]
        at hellfirepvp.astralsorcery.common.world.structure.StructureSmallShrine.generate(StructureSmallShrine.java:36) ~[StructureSmallShrine.class:?]
        at hellfirepvp.astralsorcery.common.world.WorldGenAttributeCommon.tryGenerateAtPosition(WorldGenAttributeCommon.java:65) ~[WorldGenAttributeCommon.class:?]
        at hellfirepvp.astralsorcery.common.world.WorldGenAttributeCommon.generate(WorldGenAttributeCommon.java:59) ~[WorldGenAttributeCommon.class:?]
        at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generateWithLastKnownVersion(AstralWorldGenerator.java:107) ~[AstralWorldGenerator.class:?]
        at hellfirepvp.astralsorcery.common.world.AstralWorldGenerator.generate(AstralWorldGenerator.java:85) ~[AstralWorldGenerator.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) ~[GameRegistry.class:?]
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) ~[asv.class:?]
        at ValkyrienWarfareBase.CoreMod.CallRunner.onPopulateChunk(CallRunner.java:110) ~[Valkyrien%20Warfare%200.8.999%20Stable.jar:?]
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983) ~[asv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) ~[lr.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by The-Fireplace** [comment]
Interesting. Can you provide a full list of mods, and your fml-server-latest.log/fml-client-latest.log(depending on if you're on a MP server or in SP)

**Comment by Yarden-zamir** [comment]
[fml-server-latest.log.txt](https://github.com/The-Fireplace/TickDynamic/files/1081834/fml-server-latest.log.txt)

[modlist.html.txt](https://github.com/The-Fireplace/TickDynamic/files/1081836/modlist.html.txt)

here you go

**Comment by Yarden-zamir** [comment]
anything else i can do to help?

**Comment by The-Fireplace** [comment]
Your issue is that you are using the deobf jar. That one is meant for Developers. Try [this file](https://minecraft.curseforge.com/projects/tick-dynamic/files/2435129/download).

**Comment by Yarden-zamir** [comment]
i tried that after the normal one didn't work and forgot about it sorry, here is the crash for that one 
[crash-2017-06-16_23.17.03-server.txt](https://github.com/The-Fireplace/TickDynamic/files/1081863/crash-2017-06-16_23.17.03-server.txt)
[fml-server-latest.log.txt](https://github.com/The-Fireplace/TickDynamic/files/1081866/fml-server-latest.log.txt)

**Comment by The-Fireplace** [comment]
Ok, I see the problem now. One minute, I'll fix it.

**Comment by Yarden-zamir** [comment]
what was it then?

**Comment by The-Fireplace** [comment]
I forgot to set the patcher to accept 1.10.2

**Comment by The-Fireplace** [comment]
There, it is fixed in 0.5.5. If not, let me know and I'll re-open the issue.

**Comment by Yarden-zamir** [comment]
ok, thank you! just gona sit here n refresh the page till it shows up
